### ISSUE TITLE
Tinted Glass Panes Buggy

### ISSUE THREAD

**Issue by YeraX7** [Midnighttigger/MT-CT-D#3] opened 2024-07-30 20:38 UTC
Hello! 

I love this mod; it is the perfect solution for connected textures. However, the only issue that is pretty annoying is that the **tinted glass panes** look very buggy. Can it be fixed? 

Thank you!

Proof:
 
![GlassBugg](https://github.com/user-attachments/assets/fc5feea8-3874-4b1a-a127-dd60faca3163)

**Comment by Midnighttigger** [comment] 2024-08-03 15:53
Looking at that it seams that may have been caused a mod causing models to not load as expected
Mod list would need to be known

**Comment by YeraX7** [comment] 2024-08-04 01:40
Hello! The mod list is very extensive, so I tried a fresh new profile with just the following mods, and the issue still appears. Also noticed that when I have shaders enabled, the issue is not happening.

The new mod list is:
![image](https://github.com/user-attachments/assets/58ab4a78-c0ad-47e5-8260-235b9db1c732)

And the issue still persists.

I am playing in Forge 1.20.1

**Comment by Midnighttigger** [comment] 2024-08-06 09:05
Thank you, I have reproduced the issue and will diagnose it

**Comment by Midnighttigger** [comment] 2024-08-06 09:22
It appears to be an issue with forge/neoforge on 1.20 but not an issue on fabric. I'll look at potentially fixing it in V4 as the models I use have overlapping textures that in reality shouldn't effect it but do

**Comment by Midnighttigger** [comment] 2024-08-06 14:40
It has been fixed and if something still isnt rignt please report it because I may not know that some bugs existed
This bug came about because I was making the resourcepack using fabric and not testing it on forge which resulted in this issue but it should be fixed with V4

**Closed by Midnighttigger** 2024-08-06 14:40 UTC
